#!/usr/bin/env python3
"""
Generate JS versions of the JSON data so the app works when opened directly from
disk (file://), where fetch() is blocked. Each file assigns to a window global;
the app loads them via <script> injection (which works over file:// AND http),
falling back to fetch only if needed.

Re-run after editing any data:  python tools/build-data.py
"""
import json, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def write_js(obj, out_path, statement):
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("/* AUTO-GENERATED by tools/build-data.py — do not edit by hand. */\n")
        f.write(statement.replace("{json}", json.dumps(obj, ensure_ascii=False)))
        f.write("\n")
    print("wrote", os.path.relpath(out_path, ROOT), f"({os.path.getsize(out_path)//1024} KB)")


def load(path):
    return json.load(open(path, encoding="utf-8"))


def main():
    # Campaigns
    write_js(load(os.path.join(ROOT, "data", "campaigns.seed.json")),
             os.path.join(ROOT, "data", "campaigns.seed.js"),
             "window.__CAMPAIGNS_SEED__ = {json};")

    # Product images
    if os.path.exists(os.path.join(ROOT, "data", "product-images.json")):
        write_js(load(os.path.join(ROOT, "data", "product-images.json")),
                 os.path.join(ROOT, "data", "product-images.js"),
                 "window.__PRODUCT_IMAGES__ = {json};")

    # Finder datasets → data/finders/<slug>.js registering into window.__FINDERS__
    finder_files = {
        "briefkasten": "briefkasten-finder.json",
        "paketboxen": "paketboxen-finder.json",
        "muelltonnenbox": "muelltonnenbox-finder.json",
        "tuersprechanlagen": "tuersprechanlagen-finder.json",
        "sicherheitstechnik": "sicherheitstechnik-finder.json",
        "tuerklingel": "tuerklingel-finder.json",
    }
    src_dir = os.path.join(ROOT, "Json Folder")
    for slug, fname in finder_files.items():
        src = os.path.join(src_dir, fname)
        if not os.path.exists(src):
            print("skip (missing):", fname); continue
        write_js(load(src),
                 os.path.join(ROOT, "data", "finders", slug + ".js"),
                 "window.__FINDERS__=window.__FINDERS__||{};window.__FINDERS__['" + slug + "']={json};")


if __name__ == "__main__":
    main()
